### ISSUE TITLE
feat: allow specifying a custom CWD for compiler command in linter

### ISSUE THREAD

**Issue by emanspeaks** [fortran-lang/vscode-fortran-support#1018]
### Is there an existing request for this?

- [X] I have searched the existing issues

### I have tried the Pre-Release of the extension.

- [X] Feature is not present in the latest Pre-Release

### Feature Request

Currently, when the compiler is called for linting, the process is spawned with the cwd set to the location of the current file being linted.  Instead, due to the issue discussed [here](https://fortran-lang.discourse.group/t/annoying-i90-i-files-when-using-ifort-compiler/4716/20), it would be better to supply a location for the compiler to run so we could, for example, have the compiler execute from a temp directory and dump the nuisance FPP outputs there.  There may be other use cases as well.

**Comment by gnikit** [comment]
I don't think this is a good idea since we would have to change how all queries to the linter work in order to circumvent a bug for a single compiler vendor (that will be fixed at some point). Fundamentally, my issue with this feature is that the user expects the linter to run in the file's CWD. We cannot make any assumptions if they rely or don't on this CWD, maybe they have preprocessor includes, maybe they use a custom command to generate some files, or maybe they use the Compile/Debug Current File feature and their input data is no longer available in the temporary location. Covering all these cases without creating source duplicates would be a nightmare.

With regards to Intel's incorrectly generated intermediate files, I would probably consider adding a patch-function that physically deletes them/moves the to the temporary cache. So in the future when Intel fixes their bug we could simply delete the function.

**Comment by gnikit** [comment]
I will be closing this, feel free to comment here to continue the discussion.

**Comment by emanspeaks** [comment]
This bug has been present in ifort for at least two years, so I don't think it's one they will be fixing anytime soon :-(

I think if someone has set this setting, it's implied that the user knows what they're doing since it is an advanced feature.  The burden is on the user to ensure they have their include paths configured correctly, but that burden was already there even in the current implementation.  Furthermore, if the code is in a read-only location, the linter will fail since it cannot write to that directory and provide confusing messages to the user.  I think there is still a use case for this functionality.  The patch function to delete/move the files is an inelegant solution to the problem compared to just changing the CWD, but i'll take what i can get if it means not having these files in the cache directory i want them to be in, heh.
