### ISSUE TITLE
feat: Publish Modern Fortran extension to the Open-VSX extension gallery for compatibility with Code Server

### ISSUE THREAD

**Issue by RemiLacroix-IDRIS** [fortran-lang/vscode-fortran-support#1079]
### Is there an existing request for this?

- [X] I have searched the existing issues

### I have tried the Pre-Release of the extension.

- [X] Feature is not present in the latest Pre-Release

### Feature Request

Hello,

Code Server (web-based version of VSCode) cannot use the official extension marketplace and is using instead the Open-VSX extension gallery: https://coder.com/docs/code-server/latest/FAQ#why-cant-code-server-use-microsofts-extension-marketplace.

Would it be possible to publish the Modern Fortran extension on it so that it's possible to use it in Code Server?

Best regards,
Rémi Lacroix

**Comment by gnikit** [comment]
Please see
- https://github.com/fortran-lang/vscode-fortran-support/issues/190
- https://github.com/fortran-lang/vscode-fortran-support/issues/240

I will look into this, but I suspect it will not be possible for the same reason (C/C++ extension). I might look into patching the `package.json`, but I really hate this idea since it will make parts of the extension unusable.

**Comment by RemiLacroix-IDRIS** [comment]
Closing as duplicate, sorry I search for open issues with "code server" and not Open VSX.
