### ISSUE TITLE
Language Server doesn't recognize structures

### ISSUE THREAD

**Issue by sdsnatcher** [fortran-lang/vscode-fortran-support#571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The linter seems to be not recognizing structures. We have many of them on a huge legacy code. Here are some an examples:

```
      Structure /DbTag/
      Integer*4      Name(SZ_TAG)
      Integer*4      Id
      Integer*4      Fnt(SZ_FNT)
      End Structure

      Structure /DbValue/
      Real*4         Value
      Integer*4      Status
      Integer*4      TimeStamp  ! included
      Integer*4      Action
      End Structure

      Structure /MsgValue/
      Integer*4      Mensagem(SZ_MSG)
      Integer*4      Status
      End Structure

```

And the the following problems are reported by the linter:

**Unexpected end statement: No open scopes
Unexpected end statement: No open scopes
Variable "Status" declared twice in scope
Unexpected end statement: No open scopes**

----

The same code compiles without issues on gfortran 11.2.0.

### Expected Behaviour

Should be able to recognize structures.

### Version of Modern Fortran

3.2.0

### Version of Visual Studio Code

1.69.0

### Platform and Architecture

Windows-10

### Additional Information

I have the following linter arguments configured on settings.json:

```
    "fortran.linter.extraArgs": [
        "-fdec",
        "-finit-local-zero",
        "-fno-underscoring",
        "-Wuninitialized"
      ],
```

**Comment by gnikit** [comment]
The diagnostics you are reporting I think come from `fortls` not the linter (gfortran). The reason why you get these errors is because `STRUCTURE` and `RECORD` are not part of the Fortran Standard and are vendor extensions. I think they even predate the Fortran 90.

I am not sure what can be done about this. Given that this is not part of the standard you can try and open a PR in fortls: https://github.com/gnikit/fortls as long as their implementation is not intrusive and does not require other parts of the codebase to change.

**Comment by sdsnatcher** [comment]
I´ll try to report there. Thanks!
