### ISSUE TITLE
feat: support virtualenv

### ISSUE THREAD

**Issue by pums974** [fortran-lang/vscode-fortran-support#656]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature Request

I have multiple project and I make an extensive use of python venv.

It would be nice if the extension could use the fortls and fprettiify (and findent ?) from the venv defined in vscode

**Comment by gnikit** [comment]
You can do this with the python extension and adding venv to the PATH that the vscode terminal has access to, or with project specific/workspace settings. Adding that kind of Python support to the Fortran extension is I am afraid well outside the scope of the extension, at least for the time being.

**Comment by pums974** [comment]
can you be more specific about the "specific/workspace settings" ? Do you mean that I should put absolute path of fortls in the workspace/settings.json ? I tried relative path without success and full path is not really convenient for a project with multiple developers.

**Comment by gnikit** [comment]
There is not much point for having `fortls` being a project dependency and installing it via a venv vs installing it in the default pip location, which should be reachable in your PATH. I believe there is a way to propagate the venv variables to the VS Code instance, not just the Python extension. How that's done has changed a few times over the years so some googling should lead you to the relevant pages.

As for the Modern Fortran extension, most settings are defined with absolute paths. That is necessary when working with multiroot workspaces. Having said that, there are internal VS Code variables that one can use that get resolved internally like `${workspaceFolder}`. For `fortls` we seem to not be using them so that's why the relative path to `fortls` is not working.
I will fix this in an upcoming release.

**Comment by pums974** [comment]
Thanks, I saw in the new pre-release 3.4.0 that you added `path variable resolution for fortls` and `local path resolution`. So I gave it another shot.

With
-  `"fortran.fortls.path": "venv/bin/fortls"`
- `"fortran.fortls.path": "./venv/bin/fortls"`
- `"fortran.fortls.path": "./venv/bin/"`
- `"fortran.fortls.path": "venv/bin/"`
I have a message that said that fortls is not installed

And with `"fortran.fortls.path": "${workspaceFolder}/venv/bin/fortls"` I have a new message:
![image](https://user-images.githubusercontent.com/1005109/194056216-3ddd7438-5460-4580-8d31-8a4b5b157e75.png)

and the following lines in the logs:
```
[ERROR - 1:57:25 PM] [lsp.client] Unable to launch LS to check version:
[ERROR - 1:57:25 PM] spawnSync /Data/WORK/Projets/arbalete/${workspaceFolder}/venv/bin/fortls ENOENT
Error: spawnSync /Data/WORK/Projets/arbalete/${workspaceFolder}/venv/bin/fortls ENOENT
	at Object.spawnSync (node:internal/child_process:1111:20)
	at spawnSync (node:child_process:834:24)
	at n.FortlsClient.getLSVersion (/home/pouxa/.vscode/extensions/fortran-lang.linter-gfortran-3.4.0/dist/extension.js:2:184404)
	at n.FortlsClient.didOpenTextDocument (/home/pouxa/.vscode/extensions/fortran-lang.linter-gfortran-3.4.0/dist/extension.js:2:181204)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
``` 

`/Data/WORK/Projets/arbalete` being my `workspaceFolder`


Do you want me to open another ticket, or is it fine to continue discussing here ?

**Comment by gnikit** [comment]
@pums974 Fixed in https://github.com/fortran-lang/vscode-fortran-support/pull/694. Will issue another pre-release today

**Comment by gnikit** [comment]
Standalone binaries like fortls, findent, fprettify should be okay with the local path resolution I included. Please have a test with the latest pre-release 3.4.2022100613. 

I will be closing this now since wider support for virtual environments i.e. sharing variables between a venv and Modern Fortran, is not something that would improve or even add to the existing functionality of the extension. Currently we don't have a use for it.

We might in the future if there is a use case, but for this to be implemented we would either need a volunteer to do the work or someone to sponsor this project since it would be at least 100h of work (split between design, implementation, writing tests and bug triage).

**Comment by pums974** [comment]
It seems to be working.
Thanks !
